include:
  - "test.yaml"
  - "toolchain.yaml"

project:
  Lattice:
    description: "Another build system for C++ based solely on configuration files."
    homepage: "https://github.com/proatgram/Lattice"
    version: 0.1
    default_toolchain: g++
    requires:
      - libcurl:
          version: ">=8"
          provider: "pkg-config"
          optional: true

Lattice:
  binary:
    lattice:
      output_name: "lattice"
      sources: ["src/main.cpp"]
      dependencies:
        private: [Utils@Lattice, Plugins@Lattice]
    SomeOtherBinary:
      sources: ["src/other/main.cpp"]
  library:
    Utils:
      type: static
      sources: ["src/Utils.cpp"]
      headers:
        public:
          - "include/Utils.hpp"
    Plugins:
      units:
        export:
          - "modules/Plugins.cppm"
      sources:
        - "src/modules/Plugins.cpp"
      dependencies:
        public: [Utils@Lattice]

